#!/bin/bash

wmfocus --font "Readex Pro":50 --textcolor "#ea9a97" --textcoloralt "#c4a7e7" --bgcolor "#232136" --textcolorcurrent "#c4a7e7" --textcolorcurrentalt "#ea9a97" --bgcolorcurrent "#232136" --offset "8,30"
